export type { SendMessageParams } from './send-message.js';
export type { ForwardMessageParams } from './forward-message.js';
export type { CopyMessageParams } from './copy-message.js';
export type { SendPhotoParams } from './send-photo.js';
export type { SendAudioParams } from './send-audio.js';
export type { SendDocumentParams } from './send-documents.js';
export type { SendVideoParams } from './send-video.js';
export type { SendAnimationParams } from './send-animation.js';
export type { SendVoiceParams } from './send-voice.js';
export type { SendVideoNoteParams } from './send-video-note.js';
export type { Media, SendMediaGroupParams } from './send-media-group.js';
export type { SendLocationParams } from './send-location.js';
export type { EditMessageLiveLocationParams } from './edit-message-live-location.js';
export type { StopMessageLiveLocationParams } from './stop-message-live-location.js';
export type { SendVenueParams } from './send-venue.js';
export type { SendContactParams } from './send-contact.js';
export type { SendPollParams } from './send-poll.js';
export type { SendDiceParams } from './send-dice.js';
export type { Action, SendChatActionParams } from './send-chat-action.js';
export type { GetUserProfilePhotosParams } from './get-user-profile-photos.js';
export type { GetFileParams } from './get-file.js';
export type { BanChatMemberParams } from './ban-chat-member.js';
export type { UnbanChatMemberParams } from './unban-chat-member.js';
export type { RestrictChatMemberParams } from './restrict-chat-member.js';
export type { PromoteChatMemberParams } from './promote-chat-member.js';
export type { SetChatAdministratorCustomTitleParams } from './set-chat-administrator-custom-title.js';
export type { BanChatSenderChatParams } from './ban-chat-sender-chat.js';
export type { UnbanChatSenderChatParams } from './unban-chat-sender-chat.js';
export type { SetChatPermissionsParams } from './set-chat-permissions.js';
export type { ExportChatInviteLinkParams } from './export-chat-invite-link.js';
export type { CreateChatInviteLinkParams } from './create-chat-invite-link.js';
export type { EditChatInviteLinkParams } from './edit-chat-invite-link.js';
export type { RevokeChatInviteLinkParams } from './revoke-chat-invite-link.js';
export type { ApproveChatJoinRequestParams } from './approve-chat-join-request.js';
export type { DeclineChatJoinRequestParams } from './decline-chat-join-request.js';
export type { SetChatPhotoParams } from './set-chat-photo.js';
export type { DeleteChatPhotoParams } from './delete-chat-photo.js';
export type { SetChatTitleParams } from './set-chat-title.js';
export type { SetChatDescriptionParams } from './set-chat-description.js';
export type { PinChatMessageParams } from './pin-chat-message.js';
export type { UnpinChatMessageParams } from './unpin-chat-message.js';
export type { UnpinAllChatMessagesParams } from './unpin-all-chat-messages.js';
export type { LeaveChatParams } from './leave-chat.js';
export type { GetChatParams } from './get-chat.js';
export type { GetChatAdministratorsParams } from './get-chat-administrators.js';
export type { GetChatMemberCountParams } from './get-chat-member-count.js';
export type { GetChatMemberParams } from './get-chat-member.js';
export type { SetChatStickerSetParams } from './set-chat-sticker-set.js';
export type { DeleteChatStickerSetParams } from './delete-chat-sticker-set.js';
export type { AnswerCallbackQueryParams } from './answer-callback-query.js';
export type { SetMyCommandsParams } from './set-my-commands.js';
export type { DeleteMyCommandsParams } from './delete-my-commands.js';
export type { GetMyCommandsParams } from './get-my-commands.js';
export type { SetChatMenuButtonParams } from './set-chat-menu-button.js';
export type { GetChatMenuButtonParams } from './get-chat-menu-button.js';
export type { SetMyDefaultAdministratorRightsParams } from './set-my-default-administrator-rights.js';
export type { GetMyDefaultAdministratorRightsParams } from './get-my-default-administrator-rights.js';
// Updating messages
export type { EditMessageTextParams } from './edit-message-text.js';
export type { EditMessageCaptionParams } from './edit-message-caption.js';
export type { EditMessageMediaParams } from './edit-message-media.js';
export type { EditMessageReplyMarkupParams } from './edit-message-reply-markup.js';
export type { StopPollParams } from './stop-poll.js';
export type { DeleteMessageParams } from './delete-message.js';
// Stickers
export type { SendStickerParams } from './send-sticker.js';
export type { GetStickerSetParams } from './get-sticker-set.js';
export type { UploadStickerFileParams } from './upload-sticker-file.js';
export type { CreateNewStickerSetParams } from './create-new-sticker-set.js';
export type { AddStickerToSetParams } from './add-sticker-to-set.js';
export type { SetStickerPositionInSetParams } from './set-sticker-position-in-set.js';
export type { DeleteStickerFromSetParams } from './delete-sticker-from-set.js';
export type { SetStickerSetThumbParams } from './set-sticker-set-thumb.js';
// Inline Mode
export type { AnswerInlineQueryParams } from './answer-inline-query.js';
export type { AnswerWebAppQueryParams } from './answer-web-app-query.js';
// Payments
export type { SendInvoiceParams } from './send-invoice.js';
export type { CreateInvoiceLinkParams } from './create-invoice-link.js';
export type { AnswerShippingQueryParams } from './answer-shipping-query.js';
export type { AnswerPreCheckoutQueryParams } from './answer-pre-checkout-query.js';
// Telegram Passport
export type { SetPassportDataErrorsParams } from './set-passport-data-errors.js';
// Games
export type { SendGameParams } from './send-game.js';
export type { SetGameScoreParams } from './set-game-score.js';
export type { GetGameHighScoresParams } from './get-game-high-scores.js';
